# Generated by Django 2.2b1 on 2020-01-22 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_neigh', '0002_auto_20200122_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map_neigh.Buildings'),
        ),
    ]
