# Generated by Django 2.2b1 on 2020-01-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map_neigh', '0003_auto_20200122_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map_neigh.Buildings'),
        ),
    ]
